"""Update created_at to use server default

Revision ID: 058e4d675d98
Revises: 
Create Date: 2024-12-13 14:52:03.572054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058e4d675d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               server_default=sa.text('now()')
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               server_default=None)

    # ### end Alembic commands ###
