"""Add latest video model

Revision ID: 2466880e14fb
Revises: 328a38017886
Create Date: 2025-01-03 05:33:38.102077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2466880e14fb'
down_revision = '328a38017886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_video')
    # ### end Alembic commands ###
