"""Add sprites column for Pokemon

Revision ID: 328a38017886
Revises: f032e8371e80
Create Date: 2025-01-03 02:23:42.296555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328a38017886'
down_revision = 'f032e8371e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('sprite')

    # ### end Alembic commands ###
