"""ban

Revision ID: 3b4db1790fbb
Revises: ce1552cfd72d
Create Date: 2024-12-27 18:14:43.161760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b4db1790fbb'
down_revision = 'ce1552cfd72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bans', schema=None) as batch_op:
        batch_op.alter_column('banned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('banned_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bans', schema=None) as batch_op:
        batch_op.alter_column('banned_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('banned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
