"""Set server_default for created_at

Revision ID: cd987c765e84
Revises: 
Create Date: 2024-12-14 04:54:18.200564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'cd987c765e84'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=func.now(),  # Set the default to current timestamp
               nullable=False)  # Keep nullable=False to ensure no null values are allowed
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,  # Remove the server default on downgrade
               nullable=True)  # Allow null values during downgrade
    # ### end Alembic commands ###
