"""Add Ban model

Revision ID: ce1552cfd72d
Revises: c29f3c243ab8
Create Date: 2024-12-27 15:56:43.555272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1552cfd72d'
down_revision = 'c29f3c243ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='Violation of terms', nullable=False),
    sa.Column('banned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bans')
    # ### end Alembic commands ###
