"""Add Patreon tokens to Users model

Revision ID: e5e56132d474
Revises: ff222a929e0b
Create Date: 2024-12-28 23:01:23.827042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e56132d474'
down_revision = 'ff222a929e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patreon_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patreon_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patreon_user_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('patreon_user_id')
        batch_op.drop_column('patreon_refresh_token')
        batch_op.drop_column('patreon_access_token')

    # ### end Alembic commands ###
