"""Add Game Logo

Revision ID: eb40ba5cd67d
Revises: 2466880e14fb
Create Date: 2025-01-03 06:19:55.394218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb40ba5cd67d'
down_revision = '2466880e14fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.Text(), server_default='default', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
